package constants;

public enum Actions {
	BACK,
	NEXT,
	SCROLL,
	OPEN_FILE_CHOOSER,
	SAVE_FILE,
	
	//=============== CHOOSE
		CHOOSE_SIZE,
		CHOOSE_COLOR_IN_CHROMA,
		CHOOSE_A_COLOR,
		CHOOSE_FONT_FAMILY,
		CHOOSE_FONT_SIZE,
	
	//=============== TO WRITE
		CENTERING_THE_TEXT,
		PUT_TEXT_AT_THE_LEFT,
		PUT_TEXT_AT_THE_RIGHT,
	
	//=============== MENU
		SHOW_FILE_MENU,
		SHOW_VIEW_MENU,
		SHOW_SHAPE_MENU,
		SHOW_SIZE_MENU,
		SHOW_CHROMATIC_MENU,
		SHOW_ROTATE_MENU,
		SHOW_FONT_FAMILY_MENU,
		SHOW_FONT_SIZE_MENU,
	
	//=============== SHOW
		SHOW_STATUSBAR,
		SHOW_RULER,
		SHOW_GRIDLINES,
	
	//=============== TOOLKIT
		CUT,
		COPY,
		PASTE,
		SELECT,
		CROP,
		RESIZE,
		FLIP,
		ROTATE_RIGHT_90,
		ROTATE_LEFT_90,
		ROTATE_TO_180,
		WRITE,
		ERASE,
		FILL,
		PICK_COLOR,
		ZOOM,
		DRAW_WITH_PENCIL,
		DRAW_WITH_BRUSH,
		DRAW_A_SHAPE,
	
	//================ DRAW
		DRAW_LINE,
		DRAW_CURVE,
		DRAW_ELLIPSE,
		DRAW_RECTANGLE,
		DRAW_POLYGON,
		DRAW_ROUNDED_RECTANGLE,
		DRAW_TRIANGLE,
		DRAW_RIGHT_TRIANGLE,
		DRAW_PENTAGON,
		DRAW_HEXAGON,
	
	//================= THE REST
		NONE
	
}
